### ISSUE TITLE
default logging config

### ISSUE THREAD

**Issue by matt-farmer** [nsip/sif-xml2json#3]
Logging configuration is set in config.toml.
Current default results in immediate error message when starting service on mac:
```
2020/12/16 15:05:16 Could NOT Create File to Write: mkdir /home/user: operation not supported @ github.com/cdutwhu/debog/base.MustWriteFile
```
Logging is looking to use user-level dot file location. Generally suggest local config as default to avoid such issues, with user able to reconfigure as/if needed.

current:
```toml
Service = "sif-xml2json"
Version = "v0.1.5"
Log = "/home/user/.sif-xml2json/log/2020-12-02.log"
```
suggest:
```toml
Service = "sif-xml2json"
Version = "v0.1.5"
Log = "./log/2020-12-02.log"
```

changing this value means service starts and works correctly on Mac.
